version: '3.1'
services:

  partnersLk:
    build: ./src/main
     container_name:lk
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://10.13.15.16;database=partnerslk;characterEncoding=UTF-8;encrypt=true;trustServerCertificate=true
    networks:
      - partnerslk

networks:
  partnersLk:
    driver: bridge
