name: Build and deploy the app

on:
  push:
    branches:
      - develop
    workflow_dispatch:

jobs:
  windows-auth-tsqlt:
    name: SQL and Java
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: chriseaton/adventureworks:latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: 3uuiCaKxfbForrK

    steps:
      - uses: actions/checkout@v2

      - name: Install tSQLt with SQL auth on tempdb
        uses: lowlydba/tsqlt-installer@v1
        with:
          sql-instance: localhost
          database: tempdb
          version: latest
          user: sa
          password: 3uuiCaKxfbForrK


      - name: Set environment variable ENV_CONTAINER_ID
        run: echo "ENV_CONTAINER_ID=$(docker ps --all --filter status=running --no-trunc --format "{{.ID}}")" >> $GITHUB_ENV

      - name: Test environment variable ENV_CONTAINER_ID
        run: echo $ENV_CONTAINER_ID

  #build:
   # runs-on: ubuntu-latest


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
            java-version: 11
            distribution: 'temurin'

      - name: Build and Run Java Application
        run: |
            export DB_URL=jdbc:sqlserver://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }};databaseName=partnersLK
              export DB_USERNAME=${{ secrets.DB_USERNAME }}
              export DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Build with Maven
        run: mvn clean install

      - name: Start the app
        run: java -jar target/app.jar
