name: Build and deploy the app

on:
  push:
    branches:
      - develop
    workflow_dispatch:

jobs:
  windows-auth-tsqlt:
    name: SQL and Java
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: 3uuiCaKxfbForrK


    steps:
      - uses: actions/checkout@v2

      - name: Install DB
        uses: lowlydba/tsqlt-installer@v1
        with:
          sql-instance: localhost
          database: partnersLK
          version: latest
          user: sa
          password: 3uuiCaKxfbForrK

  #build:
   # runs-on: ubuntu-latest


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
            java-version: 11
            distribution: 'temurin'

      - name: Build and Run Java Application
        run: |
            export DB_URL=jdbc:sqlserver://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }};databaseName=partnersLK
              export DB_USERNAME=${{ secrets.DB_USERNAME }}
              export DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Build with Maven
        run: mvn clean install

      - name: Start the app
        run: java -jar target/app.jar
