name: Build and deploy the app

on:
  push:
    branches:
      - develop
    workflow_dispatch:

jobs:
  windows-auth-tsqlt:
    name: SQL and Java
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: sd$98sdANq

    steps:
      - name: Create MS SQL Database
        run: |
              sudo apt-get update && sudo apt-get install -y mssql-tools
              /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'sd$98sdANq' -Q 'CREATE DATABASE partnersLK'

  #build:
   # runs-on: ubuntu-latest


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
            java-version: 11
            distribution: 'temurin'

      - name: Build and Run Java Application
        run: |
            export DB_URL=jdbc:sqlserver://${{ secrets.DB_HOST }}:${{ secrets.DB_PORT }};databaseName=partnersLK
              export DB_USERNAME=${{ secrets.DB_USERNAME }}
              export DB_PASSWORD=${{ secrets.DB_PASSWORD }}

      - name: Build with Maven
        run: mvn clean install

      - name: Start the app
        run: java -jar target/partnerslk-0.0.1-SNAPSHOT.jar
